import type { NeighborhoodId } from "./types";

export const NEIGHBORHOODS: Record<
  NeighborhoodId,
  { id: NeighborhoodId; ar: string; en: string; aliases: string[] }
> = {
  hittin: {
    id: "hittin",
    ar: "حطين",
    en: "Hittin",
    aliases: [
      "حطين",
      "هيتين",
      "هتين",
      "هاتين",
      "hittin",
      "hitteen",
      "hateen",
      "hitin",
      "heteen",
      "hiteen",
    ],
  },
  "al-malqa": {
    id: "al-malqa",
    ar: "الملقا",
    en: "Al Malqa",
    aliases: [
      "الملقا",
      "ملقا",
      "المالقا",
      "malqa",
      "malga",
      "al malqa",
      "al-malqa",
      "almalqa",
    ],
  },
  "al-nakheel": {
    id: "al-nakheel",
    ar: "النخيل",
    en: "Al Nakheel",
    aliases: [
      "النخيل",
      "نخیل",
      "nakheel",
      "nakhil",
      "al nakheel",
      "al-nakheel",
      "al nakhil",
      "alnakheel",
    ],
  },
  "al-yasmin": {
    id: "al-yasmin",
    ar: "الياسمين",
    en: "Al Yasmin",
    aliases: [
      "الياسمين",
      "ياسمين",
      "yasmin",
      "yasmeen",
      "al yasmin",
      "al-yasmin",
      "al yasmeen",
      "alyasmin",
    ],
  },
  olaya: {
    id: "olaya",
    ar: "العليا",
    en: "Olaya",
    aliases: [
      "العليا",
      "عليا",
      "olaya",
      "ulayya",
      "olaia",
      "oleya",
      "ulaya",
      "al olaya",
      "al-olaya",
    ],
  },
  sulimaniyah: {
    id: "sulimaniyah",
    ar: "السليمانية",
    en: "Sulimaniyah",
    aliases: [
      "السليمانية",
      "سليمانية",
      "sulimaniyah",
      "sulaymaniyah",
      "sulaymaniyya",
      "suleimaniyah",
      "sulaymaniya",
      "al sulimaniyah",
    ],
  },
  "al-wurud": {
    id: "al-wurud",
    ar: "الورود",
    en: "Al Wurud",
    aliases: [
      "الورود",
      "ورود",
      "wurud",
      "al wurud",
      "al-wurud",
      "al-woroud",
      "woroud",
      "worood",
      "alwurud",
    ],
  },
  "al-rabwah": {
    id: "al-rabwah",
    ar: "الربوة",
    en: "Al Rabwah",
    aliases: [
      "الربوة",
      "ربوة",
      "rabwah",
      "al rabwah",
      "ar rabwah",
      "al-rabwah",
      "ar-rabwah",
      "rabwa",
      "alrabwah",
    ],
  },
  "al-rabi": {
    id: "al-rabi",
    ar: "الربيع",
    en: "Al Rabi",
    aliases: [
      "الربيع",
      "ربيع",
      "rabi",
      "ar rabi",
      "al rabi",
      "al-rabi",
      "ar-rabi",
      "rabie",
      "alrabi",
    ],
  },
  "al-masif": {
    id: "al-masif",
    ar: "المصيف",
    en: "Al Masif",
    aliases: [
      "المصيف",
      "مصيف",
      "masif",
      "massif",
      "al masif",
      "al-masif",
      "al massif",
      "al-massif",
      "almasif",
    ],
  },
  "al-rahmaniyyah": {
    id: "al-rahmaniyyah",
    ar: "الرحمانية",
    en: "Al Rahmaniyyah",
    aliases: [
      "الرحمانية",
      "رحمانية",
      "rahmaniyyah",
      "rahmaniyah",
      "ar rahmaniyyah",
      "al rahmaniyyah",
      "al-rahmaniyyah",
      "ar-rahmaniyyah",
      "rahmaniya",
      "alrahmaniyyah",
    ],
  },
  "as-sahafah": {
    id: "as-sahafah",
    ar: "الصحافة",
    en: "Al Sahafah",
    aliases: [
      "الصحافة",
      "صحافة",
      "sahafah",
      "al sahafah",
      "as sahafah",
      "al-sahafah",
      "as-sahafah",
      "sahafa",
      "alsahafah",
    ],
  },
  kafd: {
    id: "kafd",
    ar: "كافد",
    en: "KAFD",
    aliases: ["كافد", "kafd", "kafed", "king abdullah financial district"],
  },
  diriyah: {
    id: "diriyah",
    ar: "الدرعية",
    en: "Diriyah",
    aliases: [
      "الدرعية",
      "درعية",
      "diriyah",
      "al diriyah",
      "ad diriyah",
      "al-diriyah",
      "ad-diriyah",
      "diriya",
      "dereiyah",
    ],
  },
  "al-narjis": {
    id: "al-narjis",
    ar: "النرجس",
    en: "Al Narjis",
    aliases: [
      "النرجس",
      "نرجس",
      "narjis",
      "an narjis",
      "al narjis",
      "al-narjis",
      "an-narjis",
      "alnarjis",
      "narjes",
      "nargis",
      "narges",
    ],
  },
  "al-mughrizat": {
    id: "al-mughrizat",
    ar: "المغرزات",
    en: "Al Mughrizat",
    aliases: [
      "المغرزات",
      "مغرزات",
      "mughrizat",
      "al mughrizat",
      "al-mughrizat",
      "almughrizat",
      "mughrazat",
    ],
  },
  ghirnatah: {
    id: "ghirnatah",
    ar: "غرناطة",
    en: "Ghirnatah",
    aliases: [
      "غرناطة",
      "غرناطه",
      "ghirnatah",
      "granada",
      "gharnata",
      "ghernata",
      "al ghirnatah",
      "al-ghirnatah",
      "gharnatah",
    ],
  },
  "al-shohda": {
    id: "al-shohda",
    ar: "الشهداء",
    en: "Al Shohda",
    aliases: [
      "الشهداء",
      "شهداء",
      "shohda",
      "shuhada",
      "al shohda",
      "al-shohda",
      "al shuhada",
      "al-shuhada",
      "ash shohda",
      "ash-shohda",
      "alshohda",
      "shuhadaa",
    ],
  },
  "al-safa": {
    id: "al-safa",
    ar: "الصفا",
    en: "Al Safa",
    aliases: [
      "الصفا",
      "صفا",
      "safa",
      "al safa",
      "al-safa",
      "alsafa",
    ],
  },
  "al-rawdah": {
    id: "al-rawdah",
    ar: "الروضة",
    en: "Al Rawdah",
    aliases: [
      "الروضة",
      "روضة",
      "الروضه",
      "روضه",
      "rawdah",
      "rawda",
      "al rawdah",
      "al-rawdah",
      "ar rawdah",
      "ar-rawdah",
      "alrawdah",
    ],
  },
  qurtubah: {
    id: "qurtubah",
    ar: "قرطبة",
    en: "Qurtubah",
    aliases: [
      "قرطبة",
      "قرطبه",
      "qurtubah",
      "qurtoba",
      "al qurtubah",
      "al-qurtubah",
      "qurtuba",
      "cordoba",
    ],
  },
  "an-nazhah": {
    id: "an-nazhah",
    ar: "النزهة",
    en: "An Nuzhah",
    aliases: [
      "النزهة",
      "النزهه",
      "نزهة",
      "نزهه",
      "nuzhah",
      "nazhah",
      "an nuzhah",
      "an-nuzhah",
      "an nazhah",
      "an-nazhah",
      "nuzha",
      "al nuzhah",
      "alnuzhah",
    ],
  },
};

export function neighborhoodLabel(
  id: NeighborhoodId,
  language: "ar" | "en",
): string {
  return language === "ar" ? NEIGHBORHOODS[id].ar : NEIGHBORHOODS[id].en;
}

export function isNeighborhoodId(value: string): value is NeighborhoodId {
  return Object.prototype.hasOwnProperty.call(NEIGHBORHOODS, value);
}
